<script type="text/javascript" src="<?php echo base_url('public/') ?>js/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/modernizr.custom.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/jquery.dlmenu.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/bootstrap-select.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/jquery-plugin-collection.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/jquery.backstretch_video.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/owl-carousel.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.actions.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.carousel.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.kenburn.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.layeranimation.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.migration.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.navigation.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.parallax.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.slideanims.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev/revolution.extension.video.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/timecircles.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/main.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/js-functions.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/rev_slider.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/lightbox-plus-jquery.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('public/') ?>js/cavid.js"></script>
